---
title: "MG and kmeans"
author: "Jiayi Shen (js5354)"
date: "4/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


# Multivariate Guassian 
```{r}
EM_MG_algrm <- function(data, ncluster){

  #setting
  data <- as.matrix(data) %>% scale()
  N <- nrow(data)
  q <- ncol(data)
  p_j <- rep(1/ncluster, ncluster)
  mu <-  data[sample(N, ncluster),  ] %>% as.matrix()   
  covmat <- diag(ncol(data))
  
  covList <- list()
  for(i in 1:ncluster){
    covList[[i]] <- covmat
  }
 
  count=1
  while(count <100){
    mu0 <- mu
    
    # E-step: Evaluate posterior probability, gamma
    gamma <- c()
    for(j in 1:ncluster){
      gamma2 <- apply(data,1, mvtnorm::dmvnorm, mean = mu[j,], sigma = covList[[j]])
      gamma <- cbind(gamma, gamma2)
    }
    
    # M- step: Calculate mu
    tempmat <- matrix(rep(p_j,N),nrow=N,byrow = T)
    r <- (gamma * tempmat) / rowSums(gamma * tempmat)  
    mu <- t(r) %*% data / colSums(r) 
    
    # M- step: Calculate Sigma and p
    for(j in 1:ncluster){
      sigma <- matrix(rep(0,q^2),ncol=q)
      for(i in 1:N){
        sigma = sigma + r[i,j] * (data[i,]-mu0[j,]) %*% t(data[i,]-mu0[j,])   
      }
      covList[[j]] <- sigma/sum(r[,j]) 
    }
    p_j <- colSums(r)/N
    count = count + 1
  }
  
  cluster <- which(r == apply(r, 1, max), arr.ind = T)
  cluster <- cluster[order(cluster[,1]),]
  return(list(mu = mu,covList = covList, p_j = p_j,cluster = cluster))
}
```

Try different number of mixtures

```{r}
#try # of mixture components = 3,4,5,6
set.seed(8160)
countryname <- res_df$country
countryname 
model_1 <- EM_MG_algrm(res_df[,c("a", "b", "c")], 3)
model_2 <- EM_MG_algrm(res_df[,c("a", "b", "c")], 4)
model_3 <- EM_MG_algrm(res_df[,c("a", "b", "c")], 5)
model_4 <- EM_MG_algrm(res_df[,c("a", "b", "c")], 6)
em_result_1 <- cbind(countryname, model_1$cluster[,2])
em_result_2 <- cbind(countryname, model_2$cluster[,2])
em_result_3 <- cbind(countryname, model_3$cluster[,2])
em_result_4 <- cbind(countryname, model_4$cluster[,2])
```


# K-means
```{r}
set.seed(8160)
kmeans_model_1 <- kmeans(res_df[,c("a", "b", "c")], 3)
kmeans_model_2 <- kmeans(res_df[,c("a", "b", "c")], 4)
kmeans_model_3 <- kmeans(res_df[,c("a", "b", "c")], 5)
kmeans_model_4 <- kmeans(res_df[,c("a", "b", "c")], 6)
kmeans_result_1 <- cbind(countryname, kmeans_model_1$cluster)
kmeans_result_2 <- cbind(countryname, kmeans_model_2$cluster)
kmeans_result_3 <- cbind(countryname, kmeans_model_3$cluster)
kmeans_result_4 <- cbind(countryname, kmeans_model_4$cluster)
```

For me I think gaussian mixture clustering is better.