---
title: "Data cleaning and Newton"
author: "Jiayi Shen (js5354)"
date: "4/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
covid_old = read_csv("covid19-1.csv") %>% 
  mutate(Date = as.Date(Date, "%m/%d/%Y")) %>% 
  janitor::clean_names() %>% 
  group_by(country_region, date) %>% 
  summarize(confirmed_cases = sum(confirmed_cases)) %>% 
  filter(confirmed_cases > 0) %>% 
  mutate(earliest = min(date), 
         days = as.integer(date - earliest)) 

series_df = 
  read_csv("time_series_covid19_confirmed_global_0429.csv") %>% 
  select(-Lat, -Long) 
date_varname = series_df %>% select(-"Province/State", -"Country/Region") %>% names()

covid = 
  series_df %>% 
  rename(province_state = "Province/State",
         country_region = "Country/Region") %>% 
  group_by(country_region) %>%
  summarize_at(date_varname, sum) %>% 
  gather(key = "date", value = "confirmed_cases", "1/22/20":"4/29/20") %>% 
  filter(confirmed_cases != 0) %>% 
  mutate(date = paste0(date, "20"),
         date = as.Date(date, "%m/%d/%Y")) %>% 
  arrange(country_region, date) %>% 
  mutate(earliest = min(date), 
         days = as.integer(date - earliest)) 


covid %>% filter(country_region == "Australia")

#View(covid)
place_list = unique(covid$country_region)
place_list

covid %>% 
  filter(country_region %in% c("China", "Australia", "France", "Korea, South")) %>% 
  ggplot(aes(x = days, y = confirmed_cases)) +
    geom_point() +
    facet_grid(~country_region)
```

```{r}
## Non-linear least square fitting using `nls`

china.fit <- nls(confirmed_cases ~ SSlogis(days, Asym, xmid, scal), 
             data = filter(covid, country_region == "China"))
summary(china.fit)

coef(china.fit)[1]
```

# Newton-Raphson
```{r}
# difference between beta1 and beta2
beta_norm = function(beta1, beta2) {
  # beta1 and beta2 are p*1 vectors
  norm(as.matrix(beta1 - beta2), "F")
}

# loglik
logisticstuff <- function(X, Y, a, b, c) {
  estuff = exp(-b*(X-c))
  
  # sum of squares at current value
  r <- Y - a/(1+estuff)
  sumsq <- sum(r^2)
  
  da = sum(r*(-1/(1+estuff)))
  db = sum(r*(-a*(X-c)*estuff/(1+estuff)^2))
  dc = sum(r*(a*b*estuff/(1+estuff)^2))
  
  # gradient at betavec
  grad = c(da, db, dc)
  # grad.matrix = matrix(data = c(r*(-1/(1+estuff)),r*(-a*(X-c)*estuff/(1+estuff)^2), r*(a*b*estuff/(1+estuff)^2)),
  #                      nrow = 3, ncol = length(X))
    
  # Hessian at betavec
  hess.sum = 0
  # for (n in 1:length(X)){
  #   little.hess <- matrix(0, 3, 3)
  #   if((1+estuff[n])^2 == Inf) {next}
  #   dadb = estuff[n]*(-(X[n]-c))/(1+estuff[n])^2
  #   dadc = estuff[n]*b/(1+estuff[n])^2
  #   dbdb = -a*(X[n]-c)^2*estuff[n]*(estuff[n]-1)/(1+estuff[n])^3
  #   dcdc = a*b^2*estuff[n]*(1-estuff[n])/(1+estuff[n])^3
  #   dbdc = a*estuff[n]*(1-b*(X[n]-c)+(1+b*(X[n]-c))*estuff[n])/(1+estuff[n])^3
  #   
  #   little.hess[1,] = c(0, dadb, dadc)
  #   little.hess[2,] = c(dadb, dbdb, dbdc )
  #   little.hess[3,] = c(dadc, dbdc, dcdc )
  #   
  #   hess.sum = hess.sum + (Y[n] - a/(1+estuff[n]))*little.hess
  # }

  # Hess = grad.matrix %*% t(grad.matrix) + hess.sum
  Hess = diag(3)/10
  
  return(list(sumsq = sumsq, grad = grad, Hess = Hess))
}


# test
# logisticstuff(X/10, Y/1000, a = 79, b = 1, c = 2)
```





```{r}
newton = function(X, Y, func = logisticstuff, start, tol = 1000, maxiter = 200) {
  i <- 0
  cur <- start
  stuff <- func(X, Y, cur[1], cur[2], cur[3])
  res <- c(0, stuff$sumsq, cur)
  prevsumsq <- 0
  prev = rep(0,3)
  while(i < maxiter && abs(stuff$sumsq - prevsumsq) > tol) {
    i <- i + 1
    prevsumsq <- stuff$sumsq
    prev <- cur
    
    Hess = stuff$Hess
    # Hess.scale = 0.01*min(Hess)
    # while (!is.negative.definite(Hess)) {
    #   Hess = Hess - Hess.scale*diag(start)
    # }
    step = 1
    cur <- prev - solve(Hess) %*% stuff$grad * step
    stuff_temp <- func(X, Y, a = cur[1], b = cur[2], c = cur[3]) # log-lik, gradient, Hessian
    k=1
    while (stuff_temp$sumsq > prevsumsq & k<100) {
      #print(k)
      k = k + 1
      step = step/2
      cur <- prev - solve(Hess) %*% stuff$grad * step
      stuff_temp <- func(X, Y, a = cur[1], b = cur[2], c = cur[3]) # log-lik, gradient, Hessian
    }
    stuff = func(X, Y, cur[1], cur[2], cur[3])
    
    #print( c(i, stuff$sumsq, cur[1], cur[2], cur[3]))
    res <- rbind(res, c(i, stuff$sumsq, cur[1], cur[2], cur[3]))
  }
  
  return(res)
}
```

Apply newton on covid data by country/region
```{r}
# countries with more data
covid %>% group_by(country_region) %>% summarize(length = max(days)) %>% arrange(desc(length))

place = "Jamaica"
# place = "Japan"; place = "Korea, South"; place =  "Taiwan*"; place = "Thailand"

Y = filter(covid, country_region == place) %>% pull(confirmed_cases)
X = filter(covid, country_region == place) %>% pull(days)

digits_Y  = max(nchar(trunc(Y)))-2
a_start = max(Y/(10**(digits_Y)))
b_start = 0.3
c_start = max(median(X/10), 5)
re = newton(X = X/10, Y = Y/(10**digits_Y), func = logisticstuff, 
            start = c(a_start,b_start,c_start), 
            tol = 1e-10, maxiter = 1000)
View(re)

# Compare with nls fit
nls.fit <- nls(confirmed_cases ~ SSlogis(days, Asym, xmid, scal), 
             data = filter(covid, country_region == place))
summary(nls.fit)

# plot
logisticf = function(X, a, b, c) {
  estuff = exp(-b*(X-c)) 
  return(a/(1+estuff))
}
x = 1:600/10
y = logisticf(x, a = re[nrow(re),3]*(10**(digits_Y)), b = re[nrow(re),4]/10, c = re[nrow(re),5]*10)
df = tibble(x = x, y = y) 

ggplot() +
  geom_point(aes(x = x, y = y), data = df, color = "blue") +
  geom_point(aes(x = days, y = confirmed_cases), 
             filter(covid, country_region == place))+
  labs(title = place)
```

Apply Newton to all countries
```{r}
logit_growth = function(place){
  
  Y = filter(covid, country_region == place) %>% pull(confirmed_cases)
  X = filter(covid, country_region == place) %>% pull(days)
  
  digits_Y  = max(nchar(trunc(Y)))-2
  a_start = max(Y/(10**(digits_Y)))
  b_start = 1
  c_start = max(median(X/10), 5)
  re = newton(X = X/10, Y = Y/(10**digits_Y), func = logisticstuff, 
              start = c(a_start,b_start,c_start), 
              tol = 1e-10, maxiter = 1000)
  return(list(a = re[nrow(re),3]*(10**(digits_Y)), 
              b = re[nrow(re),4]/10, 
              c = re[nrow(re),5]*10))
  
}

#logit_growth("China")
res_df = data.frame(country= NULL, a = NULL, b = NULL, c = NULL)
for (place in place_list){
  res = logit_growth(place)
  res_df = rbind(res_df, cbind(country = place, 
                               a = res$a,
                               b = res$b,
                               c = res$c))
}
```


```{r}
# debug issues
res_df %>% 
  mutate(a = as.numeric(as.character(a)), 
         b = as.numeric(as.character(b)), 
         c = as.numeric(as.character(c))) %>% 
  filter(a < 0 | b < 0 | c<0) %>% pull(country) %>% as.character()

covid %>% filter(country_region == "Zambia") %>% View
```



